<ProfileViewWidget@BoxLayout>:

    image: image
    orientation: 'vertical'

    Image:
        id: image
        size_hint: 1,0.8
        source: 'resources/images.jpeg'

    BoxLayout:
        orientation: 'horizontal'
        Label:
            halign: 'left'
            text: 'gege'
            size_hint: (None, None)

        Label:
            halign: 'left'
            text: 'gege 2'
            size_hint: (None, None)
